dnd-side-project/dnd-mentee-4th-9-repo

backend/.gitignore, backend/app.js, backend/package.json, backend/routes/index.js
node (express) 기반의 rest api 서버 개발을 위한 기초 세팅
=> [feat] add express settings

.github/workflows/main.yml
배포 자동화를 위한 github action 작성하였습니다.
Fixes #4
=> [feat] Create main.yml file for deploying react-app

.gitignore, backend/app.js, backend/index.html, backend/package-lock.json, backend/package.json, backend/passport/index.js, backend/passport/kakaoStrategy.js, backend/public/index.css, backend/routes/auth.js, backend/routes/index.js, backend/server.js
db modeling,sns auth feature start
=> backend default setting

coding-convention.md
- 4주차 과제 코딩 컨벤션 문서화
- https://ui.toast.com/fe-guide/ko_CODING-CONVENTION
- 위 링크 기반으로 정리 -> md 파일로 추가
close #14
=> [docs] Add coding-convention.md

frontend/.gitignore, frontend/package.json, frontend/src/App.tsx, frontend/src/components/Nav/Nav.jsx, frontend/src/views/Error.jsx, frontend/src/views/Home.jsx, frontend/src/views/Plants.jsx, frontend/src/views/PlantsDetail.jsx, frontend/src/views/Subscription.jsx, frontend/src/views/Test.jsx, frontend/src/views/TestResult.jsx, frontend/yarn.lock
* 디렉터리 구조 : #17 
* [see-at front route doc](https://www.notion.so/seeat/Page-Routing-58c5cadc5b0b48c8b0c4092fd1338a1b)
page routing 작업을 했습니다.
.tsx 파일에서 `Cannot use JSX unless the '--jsx' flag is provided. ts(17004)` warning이 뜨는데, ts를 잘 몰라서 디렉터리 구조 대로 .jsx 컴포넌트로 routing한 상태예요 😢 리뷰 부탁드립니다..!
close #29
=> [feat] Set page routing

frontend/src/index.tsx, frontend/src/styles/theme.js
#34 작업 전에 공통 색상들 모아두면 편할 것 같아  provider로 추가했습니다!
```
color: ${({theme}) => theme.colors.GREEN};
```
추후 다른 스타일이나 공통 사이즈 대응할 때 여기에 추가해서 관리하면 좋을 거 같아요
=> [feat] Add theme colors

backend/models/plant.model.js
=> [feat] remove likes field in Plant model

backend/models/index.js, backend/models/plant.model.js, backend/models/tag.model.js, backend/setup.js
resolve: #39 
- fix wrong model's static method's variable. models -> db
- add looping logic for initializing & associcating for all model.js
`setup.js` 파일을 추가하였습니다. 
`node setup.js` 로 실행하면 됩니다.
```js
const db = require('./models');
const reset = async () => {
console.log('Will rewrite the mysql example database, adding some dummy data.');
await db.sequelize.sync({ force : true });
//seed 데이터를 넣는 로직을 추가 해야 함
console.log("done");
}
reset();
```
- 개발 중에만 사용하여야 하며, 강제로 기존 테이블을 모두 날리고 테이블 새로 생성 & 관계 재설정을 진행합니다.
- 주석처리한 로직에 seed 데이터를 넣기 위한 로직을 곧 짜서 넣어놓겠습니다.
또한 `models/index.js` 에서 기존
각 모델에 대해서 init & associate을 일일이 하던 로직을 루프를 돌며 자동화 하도록 하였습니다.
```js
fs
.readdirSync(__dirname)
.filter(file => {
return (file.indexOf('.') !== 0) && (file !== basename) && (file.slice(-3) === '.js');
}) …
```
=> [feat] add setup.js for reseting & adding seed data in database tables.

backend/.dockerignore, backend/Dockerfile
추후 백엔드 프로덕션 빌드를 위한 Dockerfile 추가합니다.
http://sehwanzzang.com:8080/ 
저희 jenkins 주소입니다. 제가 간단히 배포 프로세스 구축되면 가이드 드릴게요! @geneaky
=> add Dockerfile to build backend app

backend/controllers/plant.controller.js, backend/routes/plants.route.js
- change entry point of processing user's request, response
- as is : processing user's request, response in route
- to be : processing user's request in controller
@geneaky  창륜님 의견대로 유저 request, response를 처리하는 부분을 컨트롤러 로직으로 모두 옮기고,
에러에 대한것은 미들웨어로 넘기도록 리팩토링 했습니다.
동작 확인했습니다.
=> [refactor] refactoring controller logic

backend/controllers/plant.controller.js, backend/routes/plants.route.js
키워드 검색 먼저 했습니다. 
와이어프레임에 나온 것 처럼 검색 결과 리스트로 나온 값만 응답으로 보냈고 해당 클릭시 상세 정보는 아이디로 요청 보내시면 됩니다.
조회수 증가하는 로직이 조금 복잡해서 간단하게 리팩토링했습니다.
=> keyword search & view count logic refactoring

backend/.dockerignore, backend/config/config.js, backend/docker-compose.yml, backend/nginx.conf
- add docker-compose for running multiple container with oneshot
- define 4 containers for load balancing with nginx
- use nginx docker container as reverse-proxy server
express 백엔드 서버를 배포하기위한 리소스를 정의합니다.
nginx를 리버스 프록시 서버로 사용할 예정입니다.
=> [feat] add docker-compose for deploying backend

backend/controllers/plant.controller.js
resolve: #52 
sequelize 를 require 하는 부분이 누락되어서 추가합니다.
=> add sequelize import statement in plant.cotronller.js

readme.md
빌드현황을 체크 할 수 있는 Jenkins 뱃지를 추가하였습니다.
[![Build Status](http://3.34.87.77:8080/job/Deploying%20Backend%20-%20express%20REST%20API/badge/icon?subject=Backend%20Build)](http://sehwanzzang.com:8080/job/Deploying%20Backend%20-%20express%20REST%20API/)
[![Build Status](http://3.34.87.77:8080/job/Deploying%20Front-end%20REACT%20APP/badge/icon?subject=Front%20Build)](http://sehwanzzang.com:8080/job/Deploying%20Front-end%20REACT%20APP/)
빌드 성공상태일 경우 passing
실패일 경우 failed
진행중일 경우 running
이렇게 3가지 상태로 보이게 됩니다.
심심해서 했어요..
=> [feat] add build status badge with jenkins

backend/app.js, backend/controllers/tag.controller.js, backend/routes/tags.route.js
- `3.34.87.77/tags/search?keyword=쿼리스트링`
- 위와 같이 url/tags/search 라는 경로에 쿼리스트링으로 keyword를 넣었을때 해당 태그에 대한 like search를 하도록 구현했습니다.
요청 : http://localhost:4000/tags/search?keyword=%EA%B7%B8%EB%8A%98
응답 : 
```json
[
{
"id": 5,
"name": "#그늘에서",
"createdAt": "2021-02-07T10:46:43.000Z",
"updatedAt": "2021-02-07T10:46:43.000Z",
"Plants": [
{
"id": 1,
"feature": "1. <꽃> 꽃과 열매를 맺을 수 있어 열매의 맛은 바나나와 파인애플의 중간맛이에요.\n2. <잎> 큰 녹색의 구멍난 잎을 가지고 있으며 수경재배가 가능한 식물이에요.",
"warning": "1. 추위에 약해 겨울철에는 실내에서 키우는 걸 추천해요!\n2. 햇빛 방향에 따라 자라기 때문에 화분을 주기적으로 돌려주는 것이 좋아요.\n3. 2~3년에 한번씩 배수가 잘 되는 흙으로 분갈이가 필요해요.",
"place": "실내 또는 실외의 그늘진 장소",
"grow": "빠르게 자라는 편",
"difficulty": "★☆☆",
"water": "-봄, 여름, 가을에는 겉흙이 마르면 듬뿍\n-겨울에는 흙 전체가 마르면 듬뿍",
"height": "90~100cm",
"ment": "몬스테라는 크고 …
```
=> 태그 검색 기능 (태그를 검색하여 해당 태그를 갖고있는 식물 정보를 리턴

frontend/src/components/Section.jsx, frontend/src/views/TestResult.jsx
Section 컴포넌트 스타일을 잘못 바꾼것 수정했습니다!
=> [fix] Section component style

backend/controllers/plant.controller.js
식물 디테일 화면에서의 응답을 수정하였습니다.
해당 식물의 모든 태그를 확인 할 수 있는 로직을 추가하였습니다. 
예시 응답 :
```json
{
"id": 1,
"feature": "1. <꽃> 꽃과 열매를 맺을 수 있어 열매의 맛은 바나나와 파인애플의 중간맛이에요.\n2. <잎> 큰 녹색의 구멍난 잎을 가지고 있으며 수경재배가 가능한 식물이에요.",
"warning": "1. 추위에 약해 겨울철에는 실내에서 키우는 걸 추천해요!\n2. 햇빛 방향에 따라 자라기 때문에 화분을 주기적으로 돌려주는 것이 좋아요.\n3. 2~3년에 한번씩 배수가 잘 되는 흙으로 분갈이가 필요해요.",
"ment": "몬스테라는 크고 특이하게 갈라진 잎이 매력적인 친구이며, 크기도 적당해서 플랜테리어 식물로 유명하답니다. 또한 관리가 쉽고 환경 변화에 크게 예민하지 않아 식물을 키운 경험이 적은 초보 식물 집사에게 인기가 많아요. 예쁘게 자라는 모습도 눈에 잘 들어옵니다. 단, 직사광선보다는 밝은 창가가, 많은 물을 필요로 하지 않는 만큼 과습에 주의해준다면 더욱 잘 자란답니다.",
"views": 17,
"imagePath": "https://seeat-image-dev-image-bucket.s3.ap-northeast-2.amazonaws.com/%E1%84%86%E1%85%A9%E1%86%AB%E1%84%89%E1%85%B3%E1%84%90%E1%85%A6%E1%84%85%E1%85%A1.png",
"thumbnailPath": …
```
=> [feat] add returning requested plant's all tag logic

backend/controllers/plant.controller.js
전체 식물 리스트 조회에서 기존에 Tag 들의 timestamp (createdAt, updatedAt) 을 제거하고 응답을 주도록 수정했습니다.
```json
[
{
"id": 1,
"feature": "1. <꽃> 꽃과 열매를 맺을 수 있어 열매의 맛은 바나나와 파인애플의 중간맛이에요.\n2. <잎> 큰 녹색의 구멍난 잎을 가지고 있으며 수경재배가 가능한 식물이에요.",
"warning": "1. 추위에 약해 겨울철에는 실내에서 키우는 걸 추천해요!\n2. 햇빛 방향에 따라 자라기 때문에 화분을 주기적으로 돌려주는 것이 좋아요.\n3. 2~3년에 한번씩 배수가 잘 되는 흙으로 분갈이가 필요해요.",
"ment": "몬스테라는 크고 특이하게 갈라진 잎이 매력적인 친구이며, 크기도 적당해서 플랜테리어 식물로 유명하답니다. 또한 관리가 쉽고 환경 변화에 크게 예민하지 않아 식물을 키운 경험이 적은 초보 식물 집사에게 인기가 많아요. 예쁘게 자라는 모습도 눈에 잘 들어옵니다. 단, 직사광선보다는 밝은 창가가, 많은 물을 필요로 하지 않는 만큼 과습에 주의해준다면 더욱 잘 자란답니다.",
"views": 0,
"imagePath": "https://seeat-image-dev-image-bucket.s3.ap-northeast-2.amazonaws.com/%E1%84%86%E1%85%A9%E1%86%AB%E1%84%89%E1%85%B3%E1%84%90%E1%85%A6%E1%84%85%E1%85%A1.png", …
```
=> [refactor] remove timestamps in getListPlants logic's response

backend/controllers/plant.controller.js
식물 디테일 화면 응답을 수정합니다.
```json
{
"id": 1,
"feature": "1. <꽃> 꽃과 열매를 맺을 수 있어 열매의 맛은 바나나와 파인애플의 중간맛이에요.\n2. <잎> 큰 녹색의 구멍난 잎을 가지고 있으며 수경재배가 가능한 식물이에요.",
"warning": "1. 추위에 약해 겨울철에는 실내에서 키우는 걸 추천해요!\n2. 햇빛 방향에 따라 자라기 때문에 화분을 주기적으로 돌려주는 것이 좋아요.\n3. 2~3년에 한번씩 배수가 잘 되는 흙으로 분갈이가 필요해요.",
"ment": "몬스테라는 크고 특이하게 갈라진 잎이 매력적인 친구이며, 크기도 적당해서 플랜테리어 식물로 유명하답니다. 또한 관리가 쉽고 환경 변화에 크게 예민하지 않아 식물을 키운 경험이 적은 초보 식물 집사에게 인기가 많아요. 예쁘게 자라는 모습도 눈에 잘 들어옵니다. 단, 직사광선보다는 밝은 창가가, 많은 물을 필요로 하지 않는 만큼 과습에 주의해준다면 더욱 잘 자란답니다.",
"views": 3,
"imagePath": "https://seeat-image-dev-image-bucket.s3.ap-northeast-2.amazonaws.com/%E1%84%86%E1%85%A9%E1%86%AB%E1%84%89%E1%85%B3%E1%84%90%E1%85%A6%E1%84%85%E1%85%A1.png",
"thumbnailPath": …
```
=> [refactor] change plant's detail response

backend/app.js, backend/package-lock.json, backend/package.json, backend/routes/plants.route.js, backend/routes/swagger.route.js
개발 편의성을 위해서 한번 swagger 문서화를 도입해봤습니다!!
제가 기존에 있던 API 명세들 이걸로 한번 해보아볼게요 !!
=> [feat] add swagger interface

backend/routes/plants.route.js
query String 기본 Parameter로 view를 입력해놓았습니다.
=> [chore] add default queryString parameter

backend/routes/plants.route.js
=> [chore] modfiy swagger document

backend/app.js
가독성을 위해 기존 app.js를 클래스화 하였습니다!
추후 application 레벨에서의 로드밸런싱에도 활용 가능해서 수정했습니다!
테스트도 완료되었어요!!
=> [refactor] change app.js as class

backend/controllers/plant.controller.js
@1000peach 식물 디테일 화면에서는 썸네일 이미지 경로를 반환 할 필요가 없다는 의견 주셔서 반영합니다!
=> [refactor] remove thumbnail path in plant detail response

backend/jenkins/front.groovy
프론트엔드 앱을 jenkins에서 빌드 할 때 `.env` 파일을 프론트엔드 루트 디렉터리에 주입하도록 배포 프로세스 구축하였습니다.
아래는 현재 `.env` 파일 상태입니다. 보안상 PR 머지 되기 전까지만 스크린샷 공유드리고, 이후에는 삭제하도록 하겠습니다 :) 
감사합니다.
=> [chore] add .env file & adding that file in frontend/ directory

frontend/src/styles/theme.js
컬러 세팅값 변경했습니다! 
이부분 우선 pr 올려요~!
=> [feat] change colors

backend/setup.js
fixes: #112 
이미지 파일명을 한글로 수정하였습니다. 
URL enocde 이슈였던것 같아요 !
=> [bugfix] modfiy wrong image path

backend/package.json, backend/test.json
resolve : #114 
부하 테스트 로직을 작성하였습니다. 
현재 같은 호스트로부터 1초에 60번 이상 요청을 받을 경우 리젝하는 코드가 `app.js`에 들어있어서 테스트는 불가능합니다. 
추후 백엔드 테스트용 브랜치를 만들어놓고 테스트를 해야 할 것 같습니다.
테스트하고 결과 공유해드릴게요 ~!
테스트 결과 : #119
=> [chore] add test load test logic with artillery

backend/package-lock.json, backend/package.json
=> [chore]change artillery as dev dependency

backend/controllers/plant.controller.js, backend/package-lock.json, backend/package.json, backend/services/plantService.js
테스트를 위해 `controller`에서 `service layer`로 메서드 분리했습니다. 
비즈니스 로직은 service에서 수정하시면 됩니다.
=> seperate controller to service layer

backend/controllers/tag.controller.js
resolve: #122 
```json
[
{ "id": 1, "name": "💧💧💧", "type": "물주기" },
{ "id": 2, "name": "💧", "type": "물주기" },
{ "id": 3, "name": "#잎도촉촉히", "type": "물주기" },
{ "id": 4, "name": "#작은크기", "type": "크기" },
{ "id": 5, "name": "#보통크기", "type": "크기" },
{ "id": 6, "name": "#큰", "type": "크기" },
{ "id": 7, "name": "#꽃", "type": "꽃/열매" },
{ "id": 8, "name": "#열매", "type": "꽃/열매" },
{ "id": 9, "name": "#그늘에서", "type": "장소" },
{ "id": 10, "name": "#환한곳에서", "type": "장소" },
{ "id": 11, "name": "#쑥쑥자라요", "type": "속도" },
{ "id": 12, "name": "#처음모습그대로", "type": "속도" },
{ "id": 13, "name": "#적당히포근하게", "type": "온도" },
{ "id": 14, "name": "#따뜻하게", "type": "온도" },
{ "id": 15, "name": "⭐", "type": "난이도" },
{ "id": 16, "name": "⭐⭐", "type": "난이도" },
{ "id": 17, "name": "⭐⭐⭐", "type": "난이도" }
]
```
```json
[
{ "id": …
```
=> /tags 결과를 정렬하여 보내는 로직

backend/services/plantService.js
resolve : #131 
@1000peach  수정하였습니다.
@geneaky 이거 시퀄라이즈로 조인 어떻게 잘 써야할지 모르겠네요 ㅎㅎ..; 완전 우겨넣어서 했는데 추후 리팩토링 가능하시면 부탁드려요 !
=> [feat] add returning all tags while tag seraching

backend/setup.js
물주기 / 장소/ 속도/ 온도 등에 대한 태그에 필요한 이미지들 경로를 저장하였습니다.
=> [chore] add image path in plant's tag

backend/services/plantService.js, backend/setup.js
resolve : #137 
피그마 화면과 동일하게 태그를 정렬해서 응답을 보내도록 로직 추가하였습니다.
```json
{
"id": 1,
"ment": "몬스테라는 크고 특이하게 갈라진 잎이 매력적인 친구이며, 크기도 적당해서 플랜테리어 식물로 유명하답니다. 또한 관리가 쉽고 환경 변화에 크게 예민하지 않아 식물을 키운 경험이 적은 초보 식물 집사에게 인기가 많아요. 예쁘게 자라는 모습도 눈에 잘 들어옵니다. 단, 직사광선보다는 밝은 창가가, 많은 물을 필요로 하지 않는 만큼 과습에 주의해준다면 더욱 잘 자란답니다.",
"imagePath": "https://resources.seeat-plant.com/몬스테라_full.png",
"Tags": [
{
"id": 1,
"name": "💧💧💧"
},
{
"id": 5,
"name": "#보통크기"
},
{
"id": 7,
"name": "#꽃"
},
{
"id": 8,
"name": "#열매"
},
{
"id": 9,
"name": "#그늘에서"
},
{
"id": 11,
"name": "#쑥쑥자라요"
},
{
"id": 13,
"name": "#적당히포근하게"
},
{
"id": 15,
"name": "⭐"
}
]
}
```
```json
{
"id": 1,
"ment": "몬스테라는 크고 특이하게 갈라진 잎이 매력적인 친구이며, 크기도 적당해서 플랜테리어 식물로 유명하답니다. 또한 …
```
=> 피그마 화면과 동일한 순서로 태그 정렬 추가 (누락된 태그 정렬 부분 모두 정리)

backend/setup.js
=> [bugfix]change image path in setup.js

backend/setup.js
=> [feat] change 잎도촉촉히 as 잎촉촉

backend/services/plantService.js
fixes : #156 
`having` 및 `group` 절을 넣었습니다. 
```js
const findPlantsIds = await Plant.findAll({
attributes: ['id'],
include: [
{
model: Tag,
where: {
name: {
[Op.in] : plantDTO
},
},
attributes: [],
through: {
attributes: [],
},
},
],
having: sequelize.literal(`COUNT(DISTINCT Tags.name) = ${plantDTO.length}`),
group: ['id'],
});
```
지금 케이스와 같이 일치하는 태그들을 찾고, 일치하지 않는 태그가 있을 경우에 필요한 작업들입니다.
ref : https://stackoverflow.com/questions/52290036/mysql-many-to-many-relationship-with-multiple-and-condition
이번에 정말 많이 알아가네요..ㅎㅎ 
이 브랜치로 배포해둘게요 테스트 부탁드립니다 !!
```sql
SELECT `Plant`.`id` FROM `plants` AS `Plant` 
INNER JOIN ( `plantTags` AS `Tags->PlantTag` 
INNER JOIN `tags` AS `Tags` ON `Tags`.`id` = `Tags->PlantTag`.`TagId`) 
ON `Plant`.`id` = `Tags->PlantTag`.`PlantId` AND `Tags`.`name` IN ('⭐⭐⭐', …
```
=> [feat] add group & having clause for filtering result

backend/deployment/lambda/serverless.yml
=> [feat]update plant's view every 12hours

backend/app.js, backend/index.html, backend/package-lock.json, backend/routes/plants.route.js, backend/routes/tags.route.js, backend/services/plantService.js, backend/util/check.js, backend/util/key.check.js, frontend/src/api/instance.js, frontend/src/const/config.js
resolve: #98, #183 쿠키,세션 없이 api key를 사용해서 특정 요청만 받을 수 있게 처리 했습니다. 
```js
//api key 발급 (최초 1회 사용하여 .env에 등록)
const encrypt = (text) => {
try {
let iv = crypto.randomBytes(16);
let cipher = crypto.createCipheriv(
'aes-256-cbc',
Buffer.from(ENCRYPTION_KEY),
iv
);
let encrypted = cipher.update(text);
encrypted = Buffer.concat([encrypted, cipher.final()]);
return iv.toString('hex') + ':' + encrypted.toString('hex');
} catch (error) {
console.error(error);
}
};
//발급된 api key 확인 비대칭 양방향 암호화를 복호화
const decrypt = (text) => {
try {
let textParts = text.split(':');
let iv = Buffer.from(textParts.shift(), 'hex');
let encryptedText = Buffer.from(textParts.join(':'), 'hex');
let decipher = crypto.createDecipheriv(
'aes-256-cbc',
Buffer.from(ENCRYPTION_KEY),
iv
);
let decrypted = …
```
=> api key generate & encrypt,decrypt

backend/services/plantService.js
=> 키워드 검색 API 호출 응답에서 태그 타입 응답 추가

frontend/src/test/plantAPI.test.js
이번에 백엔드 코드 테스트 자동화를 `github action` 으로 구현하면서,
프론트 코드 API 호출 부분도 테스트 코드를 작성하고 이를 Github PR 올라올때마다 체크하고자 합니다. (API 서버와의 원활한 통신이 되는지 체크하는 느낌으로..)
=> 프론트엔드 API 테스트 코드 작성

backend/jenkins/front.groovy
=> [chore] add logic removing objects in s3

backend/setup.js
=> [bugfix] change tag name '#큰' -> '#큰크기'

frontend/src/components/SearchPlants/SearchResultPlant.jsx
수정 사항 보이는 것들 작업 중입니다 👩‍💻
내일 아침 전에는 머지해놓을게요.!
=> [feat] modify SearchResultPlant style

frontend/public/index.html, frontend/src/App.tsx, frontend/src/components/PlantsDetail/AllKeywords.jsx, frontend/src/components/TagList.jsx, frontend/src/const/config.js, frontend/src/lib/initialize.js, frontend/src/lib/share.js, frontend/src/views/TestResult.jsx
#107 
카카오톡 아이콘 클릭 시 테스트 결과 링크가 `?shared=true` 쿼리 스트링이 추가되어 공유됩니다.
현재 해당 브랜치로 배포해두었는데, 정상 작동 하는 거 같아서 머지되면 좋을 거 같아 pr 작성합니다.!
세환님이 이슈 작성해주셔서 같이 리뷰 요청 드렸어요!
혹시 안 되는 부분이 있거나 다른 의견 있으시면 알려주세요..!
리뷰 감사합니다 🙇‍♀️
=> 테스트 결과 카카오 공유 기능

frontend/public/index.html, frontend/src/App.tsx, frontend/src/components/PlantsDetail/AllKeywords.jsx, frontend/src/components/SearchPlants/SearchResultPlant.jsx, frontend/src/components/TagList.jsx, frontend/src/const/config.js, frontend/src/lib/initialize.js, frontend/src/lib/share.js, frontend/src/views/TestResult.jsx
* 테스트 결과 카카오 공유 기능 추가
* `Slider`에서 `TagList` ui 깨짐 현상 수정
* 식물 상세 페이지 -> 선택한 키워드 전체 보기 기능 추가 (클릭 시 해당 태그 선택한 식물 도감 페이지로 이동)
=> 발표 전 최종 수정 사항 반영
